### ISSUE TITLE
Progress Report Events for Map Import

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-map-server#23]
When and MB tiles get posted, we would like to show the user the progress of the download.

- [ ] GET Request for Progress. This should subscribe to progress event from the worker thread. Interface for progress event below:

```typescript
  interface ProgressData {
    type: 'progress'
    importId: string
    soFar: number
    total: number
  }
```

### To Note:
The progress event should be fired on import of every tile, and the front end will do the calculation of time (for the progress bar). If the progress event seems to be fired too often, we can throttle it, but that can be determined afterwards

**Comment by achou11** [comment]
Instead of using Server Sent Events, can use polling strategy for initial implementation i.e. client makes several GET requests to get updates
