### ISSUE TITLE
Add routes, api methods & e2e tests for Glyphs

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-map-server#5]
Mapbox GL maps require fonts rendered to SDFs (Signed-distance field), this makes rendering in GL fast and pretty. We need to [support this route](https://docs.mapbox.com/api/maps/fonts/):

- [ ] `GET /fonts/{font}/{start}-{end}.pbf` - where `{font}` can be a comma-separated (URL encoded) list of font names, and we should return the first available (similar to how a CSS `font-family` property works).

It is possible to render SDFs dynamically (e.g. https://github.com/mapbox/node-fontnik) but I'm wary about introducing another native library in our stack. We can download them from the Mapbox API, but that's not a great solution either.

I suggest that we generate SDFs for common fonts as part of our build process and ship them as static files included in the npm bundle. We can use node-fontnik (or maybe there is a better maintained SDF renderer out there?) for generating these at build time. We would probably need to stick to open fonts that we are able to bundle in the app. We should support some kind of fallback lookup table, so that if we do not have a font that is referenced in the `{font}` part of the URL, then we fall back to the closest equivalent.

We should also support downloading SDFs / glyphs from the Mapbox API when the user downloads a style that references a font that we do not have pre-rendered.

Maybe as an MVP, we proxy / download Mapbox rendered SDFs directly from their API. We should store these in a way that they can be shared across different styles, e.g. if we use the SWR cache then we should normalize the URL to reduce the `{font}` part to a single font name.

**Comment by achou11** [comment]
Additional technical notes:
- when creating the style:
  - need to traverse the style to find all the fonts that are being used (see https://github.com/digidem/mapbox-style-downloader/blob/master/lib/glyphs.js#L21-L53 for approximate example)
  - take the first first font name from the font stack and use it for creating the upstream url. based on testing, requesting glyphs using font names that don't exist causes the request to 404, as opposed to falling back

**Comment by achou11** [comment]
for initial version, maybe dont reference db table and just bundle a couple of open standard sdf fonts (one serif and one sans-serif) and then serve as static files

need an endpoint that is aware of common fonts and determine/guess whether to serve serif or sans-serif

**Comment by achou11** [comment]
@gmaclennan can you share thoughts on what you think would be reasonable for the first iteration of this feature? Are we strictly going to serve static files from pre-bundled sdfs or do we still want to handle getting upstream glyphs when online? (note we don't currently have anything that helps us determine online connectivity). if we get upstream glyphs, do we want to store them? (if so, in the db or as a static file?)

**Comment by achou11** [comment]
rereading the original description, maybe we can just focus supporting two things to start:

1. Serve prebundled glyphs as static files
2. Proxying requested glyphs from mapbox but NOT storing them. 

We'd do 1 in the case of offline, and 2 in the case of online

**Comment by gmaclennan** [comment]
Yes, that sounds like a reasonable approach.
