### ISSUE TITLE
Importing mbtiles without metadata `name` row fails

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-map-server#95]
If a generated mbtiles file (such as using `tl`) doesn't have a `name` row in the metadata table, importing it fails with a `SQLITE_CONSTRAINT_NOTNULL` error. The offending query is https://github.com/digidem/mapeo-map-server/blob/9457c024f518bcab0fb85a0feba4ed240c7655e1/src/lib/mbtiles_import_worker.js#L94 where we expect a `name` to be present in the extracted mbtiles metadata.

It doesn't seem that the [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) has any mention of the `name` row being standardized, so we should properly account for it being missing. Think the most proper solution would be updating the [`OfflineArea` table schema](https://github.com/digidem/mapeo-map-server/blob/9457c024f518bcab0fb85a0feba4ed240c7655e1/prisma/schema.prisma#L89) such that it allows the `name` field to be nullable.

**Comment by achou11** [comment]
ah actually, misread the spec and it actually does specify the `name ` row as a must, so maybe this isn't an issue that the map server should address 🤔

**Comment by achou11** [comment]
Pasting suggestion from @gmaclennan for potential improvements to this:

> As for a fix, I think we need at least a clear error message with steps to resolve. Since this is actually hard to resolve for a non-technical user if they are using a tool like tl which does not conform to the spec, then I wonder if we should fall back to using the filename or something?

**Comment by EvanHahn** [comment]
It seems like there are two suggested solutions:

1. If `name` is missing, error
1. If `name` is missing, add a fallback

I'm going to go with the first option, but let me know if that's wrong!

**Comment by achou11** [comment]
> It seems like there are two suggested solutions:
> 
>     1. If `name` is missing, error
> 
>     2. If `name` is missing, add a fallback
> 
> 
> I'm going to go with the first option, but let me know if that's wrong!

I think based https://github.com/digidem/mapeo-map-server/issues/95#issuecomment-1537212746 we probably should lean towards option 2 because most of the time, these mbtiles files are generated somewhat opaquely through programs like QGIS. also, (1) would require the end user to fix the file, which is not trivial unless you're familiar with messing with sqlite files 😄
